name: SRF Deployment
on:
  workflow_dispatch:
    inputs:
      stage:
        description: 'Stage (test|stage|production)'
        required: true
jobs:
  build_and_deploy:
    name: Build and Deploy ${{ github.event.inputs.stage }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: build
        run: | 
          mkdir -v build
          zip -9vr build/scanii-lambda.zip lib/ node_modules/ package* README.md LICENSE
      - name: install AWS cli
        if: ${{ github.event.inputs.stage == 'test' }}
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
      - name: deploy 
        run: |
          if [ ${{ github.event.inputs.stage }} = "test" ]
          then
            export AWS_DEPLOY_BUCKET=${{ secrets.AWS_DEPLOY_BUCKET_DEV }}
          elif [ ${{ github.event.inputs.stage }} = "stage" ]
          then
            export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID_INT }}
            export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY_INT }}
            export AWS_DEPLOY_BUCKET=${{ secrets.AWS_DEPLOY_BUCKET_INT }}
          elif [ ${{ github.event.inputs.stage }} = "production" ]
          then
            export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID_PRD }}
            export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY_PRD }}
            export AWS_DEPLOY_BUCKET=${{ secrets.AWS_DEPLOY_BUCKET_PRD }}
          else
            echo "Stage ${{ github.event.inputs.stage }} not found" 
            exit 1
          fi

          aws s3 cp build/bundle.zip s3://${AWS_DEPLOY_BUCKET}/formio-scanii/latest.zip

          #aws lambda update-function-code --function-name formio-scanii-submit-${{ github.event.inputs.stage }} --s3-bucket ${AWS_DEPLOY_BUCKET} --s3-key formio-scanii/latest.zip
          #aws lambda update-function-code --function-name formio-scanii-callback-${{ github.event.inputs.stage }} --s3-bucket ${AWS_DEPLOY_BUCKET} --s3-key formio-scanii/latest.zip

